#!/bin/bash

save_coredumps() {
    core_dir=/var/lib/graph/cores
    datestamp=$(date +"%Y-%m-%dT%H:%M:%S")
    ls /core.* >& /dev/null && have_cores=yes || have_cores=no
    if [ -d "$core_dir" -a "$have_cores" = yes ]
    then
        exec >> "$core_dir"/messages 2>&1
        echo "${HOSTNAME##*-} Saving core dump on ${HOSTNAME} at ${datestamp}"

        dst="$core_dir/$datestamp-${HOSTNAME}"
        mkdir "$dst"
        cp /usr/local/cargo/bin/graph-node "$dst"
        cp /proc/loadavg "$dst"
        dmesg -e > "$dst/dmesg"
        # Capture environment variables, but filter out passwords
        env | sort | sed -r -e 's/^(postgres_pass|ELASTICSEARCH_PASSWORD)=.*$/\1=REDACTED/' > "$dst/env"

        for f in /core.*
        do
            echo "${HOSTNAME##*-} Found core dump $f"
            mv "$f" "$dst"
        done
        echo "${HOSTNAME##*-} Saving done"
    fi
}

start_query_node() {
    export DISABLE_BLOCK_INGESTOR=true
    graph-node \
        --postgres-url "$postgres_url" \
        --ethereum-rpc $ethereum \
        --ipfs "$ipfs"
}

start_index_node() {
    # Only the index node with the name set in BLOCK_INGESTOR should ingest
    # blocks
    if [[ ${pod_name} != "${BLOCK_INGESTOR}" ]]; then
        export DISABLE_BLOCK_INGESTOR=true
    fi

    graph-node \
	    --node-id "${pod_name//-/_}" \
	    --postgres-url "$postgres_url" \
	    --ethereum-rpc $ethereum \
	    --ipfs "$ipfs"
}

start_combined_node() {
    graph-node \
        --postgres-url "$postgres_url" \
        --ethereum-rpc $ethereum \
        --ipfs "$ipfs"
}

postgres_url="postgresql://$postgres_user:$postgres_pass@$postgres_host/$postgres_db"

wait_for "$ipfs" -t 120
wait_for "$postgres_host:5432" -t 120
sleep 5

trap save_coredumps EXIT

export PGAPPNAME="${pod_name-$HOSTNAME}"

case "${node_role-combined-node}" in
    query-node)
        start_query_node
        ;;
    index-node)
        start_index_node
        ;;
    combined-node)
        start_combined_node
        ;;
    *)
        echo "Unknown mode for start-node: $1"
        echo "usage: start-node (query-node|index-node)"
        exit 1
esac
