{
 "title": "Graphnode Details",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "deployment", "label": "deployment", "query": { "query": "label_values(deployment)" } },
   {
    "name": "subgraph",
    "label": "subgraph",
    "query": {
     "query": "label_values({deployment=\"$deployment\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Chain Head",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ethereum_chain_head_number)",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Deployment Head",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(deployment_head{deployment=\"$deployment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Lag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ethereum_chain_head_number - on(network, instance) deployment_head{deployment=\"$deployment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Reverted Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "deployment_reverted_blocks{deployment=\"$deployment\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Blocks Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(deployment_head{deployment=\"$deployment\"}[5m])",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Block Processing Duration (sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "rate(deployment_block_processing_duration_sum{deployment=\"$deployment\"}[5m]) / rate(deployment_block_processing_duration_count{deployment=\"$deployment\"}[5m])",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Transact Block Duration (sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "rate(deployment_transact_block_operations_duration_sum{deployment=\"$deployment\"}[5m])/rate(deployment_trigger_processing_duration_count{deployment=\"$deployment\"}[5m])",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Deployment Sync Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(deployment_sync_secs{deployment=\"$deployment\"}[5m])",
     "legendFormat": "{{section}}"
    }
   ]
  },
  {
   "title": "Eth Requests / Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "rate(eth_rpc_request_duration_count[5m])",
     "legendFormat": "{{provider}}"
    }
   ]
  }
 ]
}