-- This file was generated by generate.sh in this directory
set search_path = public;
drop aggregate arg_min_text(text_and_value);
drop aggregate arg_max_text(text_and_value);
drop function arg_from_text_and_value(text_and_value);
drop function arg_max_agg_text(text_and_value, text_and_value);
drop function arg_min_agg_text(text_and_value, text_and_value);
drop type text_and_value;
drop aggregate arg_min_bytea(bytea_and_value);
drop aggregate arg_max_bytea(bytea_and_value);
drop function arg_from_bytea_and_value(bytea_and_value);
drop function arg_max_agg_bytea(bytea_and_value, bytea_and_value);
drop function arg_min_agg_bytea(bytea_and_value, bytea_and_value);
drop type bytea_and_value;
